### ISSUE TITLE
Docker postgres:12.2-alpine - enable pg_squeeze

### ISSUE THREAD

**Issue by micemuni** [cybertec-postgresql/pg_squeeze#35]
Hi Team,
I am using postgres:12.2-alpine docker image and now need to enable pg_squeeze extension on that docker image.
Could you please tell me how to do this for docker..??

**Comment by ahouska** [comment]
If the image contains an OS for which PG community supports yum repository (https://yum.postgresql.org/), then you only need to add the appropriate yum command to your Dockerfile. Otherwise you may need to add commands that download pg_squeeze and build it from source. Before you start creating the Dockerfile, it's probably useful to start interactive session with the docker container and find out what exactly you need to do in the shell.

**Comment by micemuni** [comment]
Yum is not supporting only apk add is working, also there is no yum package for pg_squeeze.

I am using official Postgres docker image postgres:12.2-alpine https://github.com/docker-library/postgres/blob/1d140375b6830c65cfeaac3642c7fda6d3e1b29a/12/alpine/Dockerfile

My requirement is to enable the pg_squeeze on top of that. Hope you got my point i think. Could you please tell me how do we enable here..?

**Comment by kmoppel** [comment]
@micemuni I think your best bet is to fork and add build the extension yourself. Btw, is there a real performance or other reason to prefer Alpine vs the old Debian based image?

**Comment by micemuni** [comment]
@kmoppel  Yes, done with Dockerfile forked branch
