### ISSUE TITLE
Replication slot not being consumed during initial table copy

### ISSUE THREAD

**Issue by mage2k** [cybertec-postgresql/pg_squeeze#39]
Test setup:

1. Set up 100GB pgbench_accounts table.
2. Update every row via `UPDATE pgbench_accounts SET aid = aid;`

That brings the table to 200GB, 250GB w/ thd primary key index on aid.

The server has a 750GB primary database volume with pg_wal on a separate, 70GB volume.

When testing (using v1.3) with both scheduled and ad-hoc runs I'm seeing that the replication slot is not having WAL data consumed while the initial table rebuild is happening.  Would that not require more than at least 2x the space needed for the finished table build between the new table and the WAL file build-up and much more for an active server?  Is that expected or is something perhaps off with my build/installation?

**Comment by ahouska** [comment]
Well, I don't understand you calculation exactly, but yes, some extra amount of disk space is needed (the fact that both the old and the new tables should exist at some point shouldn't be surprising though).

The problem is that we cannot apply the changes done concurrently until the initial load is complete. Another problem is that the initial load produces some WAL itself.

To solve the problem, I'm thinking of a background worker that decodes WAL during the initial load and stores the changes that need to be applied to a temporary file. This temporary file should take much less space then the corresponding WAL because WAL contains data of many other tables. In addition, the changes can be stored in the temporary file compressed.

Since you're not the first one who complains about the space, I seriously consider doing what I described here. I cannot start the coding right now, but my plan is to start by the end of the year. I'll update this report as soon as there's something to test.

**Comment by mage2k** [comment]
> Well, I don't understand you calculation exactly, but yes, some extra amount of disk space is needed (the fact that both the old and the new tables should exist at some point shouldn't be surprising though).

I'm not talking about the old + new table, but rather the new + WAL data for new table + WAL data for any other activity.  Ignoring the other activity, if I have a 200GB table that I know should be at 100GB after rebuild (i.e. 50% bloated) then by waiting to consume the WAL data from the replication slot until the new table's initial load is done this needs:

200GB for current table
100GB for new table
100GB of WAL data (at least) for new table build.

What's more, if the pg_wal directory is on a smaller drive this is downright dangerous.

> To solve the problem, I'm thinking of a background worker that decodes WAL during the initial load and stores the changes that need to be applied to a temporary file. This temporary file should take much less space then the corresponding WAL because WAL contains data of many other tables. In addition, the changes can be stored in the temporary file compressed.

I was thinking a temporary or unlogged table (unlogged would allow for easily tracking the usage externally) but that works as well!

> Since you're not the first one who complains about the space, I seriously consider doing what I described here. I cannot start the coding right now, but my plan is to start by the end of the year. I'll update this report as soon as there's something to test.

Excellent!  I wish I had the C chops to help but I haven't touched the stuff since college ;)

**Comment by ahouska** [comment]
> > To solve the problem, I'm thinking of a background worker that decodes WAL during the initial load and stores the changes that need to be applied to a temporary file. This temporary file should take much less space then the corresponding WAL because WAL contains data of many other tables. In addition, the changes can be stored in the temporary file compressed.
> 
> I was thinking a temporary or unlogged table (unlogged would allow for easily tracking the usage externally) but that works as well!

The temporary file API should allow for easier coding and it should also be easier to compress the data if it's in a file. Another problem of table is that - unless there's suitable index on it - the executor does not guarantee in which order the rows are returned by sequential scan. In fact, with the current implementation of the executor,  it's not likely for a scan not to start at the beginning table, but I don't want to keep checking the executor internals in the future again and again. (Parallel scan is not a problem here because it can be disabled easily.)

**Comment by ahouska** [comment]
I've implemented WAL processing during the initial load, although not using the background worker. So far the changes are only in the master branch, REL1_4 branch will be created soon. Please test if you can.
