### ISSUE TITLE
pg squeeze will support view and materialized view?

### ISSUE THREAD

**Issue by vasanth-santharam** [cybertec-postgresql/pg_squeeze#56]
pg squeeze will support view and materialized view?
    we are trying to optimize the memory for view and materialized view

**Comment by ahouska** [comment]
View has no storage, so pg_squeeze cannot handle it. As for materialized view, why can't you simply use the `REFRESH MATERIALIZED VIEW CONCURRENTLY` command?

**Comment by vasanth-santharam** [comment]
Thanks for information and support.
we are using "REFRESH MATERIALIZED VIEW CONCURRENTLY", we have ~1000 millions records. It takes more than 5 mins.
so that we checked the alternative.

**Comment by AnanthGopal** [comment]
Hi @ahouska ,

In Postgres, materialized views use disc space. The command REFRESH MATERIALIZED VIEW CONCURRENTLY is used to refresh a specific materialized view, but it doesn't clear out any extra space. Therefore, we used the "Vacuum" command, which removes empty space from materialized views but takes a long time in our environment because we have a lot of data. Consequently, we attempt to use pg squeeze.

**Comment by df7cb** [comment]
There is nothing to squeeze in a materialized view because there are no update/delete operations running on it. The correct way to rebuild it is `REFRESH MATERIALIZED VIEW` - if that doesn't drop the old file immediately, try running `checkpoint`.
