### ISSUE TITLE
ON CONFLICT is not supported on table mytable used as a catalog table

### ISSUE THREAD

**Issue by vmihailenco** [cybertec-postgresql/pg_squeeze#6]
Looks like I can no longer use `ON CONFLICT` on table that is being squeezed...

**Comment by ahouska** [comment]
Yes, this is because the table being squeezed must have the "user_catalog_table" option set, so that concurrent data changes are guaranteed to be available for logical decoding. This restriction should be avoidable with PostgreSQL 10, but it needs some coding on the pg_squeeze side. I consider doing it in pg_squeeze 1.1.

**Comment by ahouska** [comment]
This is fixed in the master branch. Thus it'll appear in pg_squeeze 1.1 beta which we'll release in a few weeks.
