### ISSUE TITLE
Question: How to implement on Azure

### ISSUE THREAD

**Issue by tcartwright** [cybertec-postgresql/pg_squeeze#72]
Sorry for asking this here, but I am not a postgres expert by any means. I have added your extension to our Azure PG instance, but I am at a loss as to how to implement it. I have googled how to set it up for Azure, but I have been unlucky in finding any information on how to do so. I have already enabled the extension, but that is as far as I have gotten.

Could you please provide some guidance?

![image](https://github.com/user-attachments/assets/ce0bc5a8-99e7-4905-8dd9-0752aedcd108)

- Do the squeeze tables get created automatically?
- If they do not where should I create them?

**Comment by tcartwright** [comment]
I enabled that, and restarted the server and then tried the CREATE EXTENSION and got this:

![image](https://github.com/user-attachments/assets/27dc05db-64e6-4398-91be-16fb3fe12559)

I have done this two to three times. Restart -> Create Extension

**Comment by tcartwright** [comment]
However, when I try to add it to the shared preload libraries, I get this:

> The value 'pg_availability,pg_cron,pg_stat_statements,pg_squeeze' for configuration 'shared_preload_libraries' is not valid. The allowed values are 'the ones indicated by PostgreSQL documentation'. (Code: InvalidConfigurationValue)

**Comment by ahouska** [comment]
PostgreSQL itself should not restrict the list of extensions. I think that the provider runs a fork that does. Interesting is that you are allowed to install binaries which you eventually cannot run.

Another problem is that the error message does not indicate which extension causes the error. If it worked with `pg_cron` but does not work now, then it's clearly due to `pg_squeeze`. Otherwise I suggest that you install only `pg_squeeze` and see if it works.

Nevertheless, you probably need both `pg_cron` and `pg_squeeze`. Thus you probably need to ask the provider for support.

**Comment by tcartwright** [comment]
@ahouska I agree, I believe this is completely an Azure issue at this point. Closing this. Thank you.
